---
- name: Install prometheus
  become: True
  apt:
    name: prometheus
    state: present

- name: Ensure rules directories are present
  become: True
  file:
    path: "/etc/prometheus/{{ item }}"
    state: directory
  with_items:
    - recording-rules
    - alerting-rules

- name: Configure defaults for prometheus
  become: True
  template:
    src: default.j2
    dest: /etc/default/prometheus
  notify: restart prometheus

- name: Configure prometheus
  become: True
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: Configure recording rules
  become: True
  template:
    src: rule.j2
    dest: "/etc/prometheus/recording-rules/{{ item.name }}.rule"
  with_items: prometheus_recording_rules

- name: Configure alerting rules
  become: True
  template:
    src: rule.j2
    dest: "/etc/prometheus/alerting-rules/{{ item.name }}.rule"
  with_items: prometheus_alerting_rules

- name: Configure haproxy
  become: True
  template:
    src: haproxy.conf.j2
    dest: /etc/haproxy/conf.d/50-prometheus.yml
  notify: restart haproxy
