---
- name: restart prometheus
  become: True
  systemd:
    name: prometheus
    state: restarted
    enabled: yes

- name: restart haproxy
  become: True
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
